# Generated by Django 3.0 on 2021-04-07 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usrrg',
            name='age',
            field=models.IntegerField(default=22),
        ),
        migrations.CreateModel(
            name='NewData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('pid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Emp.UsrRg')),
            ],
        ),
    ]
