# Generated by Django 3.0 on 2021-04-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0002_auto_20210407_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdata',
            name='mobile',
            field=models.IntegerField(default=9618923211),
        ),
    ]
